/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthChangePasswordIndexRouteImport } from './routes/_auth/change-password/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases/index'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases/$caseId'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthChangePasswordIndexRoute = AuthChangePasswordIndexRouteImport.update({
  id: '/change-password/',
  path: '/change-password/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/': typeof AppCasesIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/change-password/': typeof AuthChangePasswordIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases': typeof AppCasesIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/change-password': typeof AuthChangePasswordIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_auth/change-password/': typeof AuthChangePasswordIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases/$caseId'
    | '/cases/'
    | '/clients/'
    | '/dashboard/'
    | '/leads/'
    | '/users/'
    | '/change-password/'
    | '/reset-password/'
    | '/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases/$caseId'
    | '/cases'
    | '/clients'
    | '/dashboard'
    | '/leads'
    | '/users'
    | '/change-password'
    | '/reset-password'
    | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/cases/$caseId'
    | '/_app/cases/'
    | '/_app/clients/'
    | '/_app/dashboard/'
    | '/_app/leads/'
    | '/_app/users/'
    | '/_auth/change-password/'
    | '/_auth/reset-password/'
    | '/_auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/change-password/': {
      id: '/_auth/change-password/'
      path: '/change-password'
      fullPath: '/change-password/'
      preLoaderRoute: typeof AuthChangePasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthChangePasswordIndexRoute: typeof AuthChangePasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthChangePasswordIndexRoute: AuthChangePasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
